spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MYSQL
    username: alex
    password: alex
  h2:
    console:
      path: "/h2-console"
      enabled: true
  sql:
    init:
      platform: h2